remove pylint-import-requirements from pipeline (due to compatibility with pylint, see log below; relocked env with pipenv v2023.10.3 on python v3.11.2)
> ##[group]Run pipenv run pylint --load-plugins=pylint_import_requirements "$(cat *.egg-info/top_level.txt)"
> …
> Traceback (most recent call last):
>   File "/home/runner/.local/share/virtualenvs/python-manchester-code-EDwhn3uB/bin/pylint", line 8, in <module>
>     sys.exit(run_pylint())
>   File "/home/runner/.local/share/virtualenvs/python-manchester-code-EDwhn3uB/lib/python3.8/site-packages/pylint/__init__.py", line 34, in run_pylint
>     PylintRun(argv or sys.argv[1:])
>   File "/home/runner/.local/share/virtualenvs/python-manchester-code-EDwhn3uB/lib/python3.8/site-packages/pylint/lint/run.py", line 155, in __init__
>     linter.load_plugin_modules(self._plugins)
>   File "/home/runner/.local/share/virtualenvs/python-manchester-code-EDwhn3uB/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 380, in load_plugin_modules
>     module = astroid.modutils.load_module_from_name(modname)
>   File "/home/runner/.local/share/virtualenvs/python-manchester-code-EDwhn3uB/lib/python3.8/site-packages/astroid/modutils.py", line 194, in load_module_from_name
>     module = importlib.import_module(dotted_name)
>   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/runner/.local/share/virtualenvs/python-manchester-code-EDwhn3uB/lib/python3.8/site-packages/pylint_import_requirements/__init__.py", line 28, in <module>
>     from pylint.interfaces import IAstroidChecker, ITokenChecker
> ImportError: cannot import name 'IAstroidChecker' from 'pylint.interfaces' (/home/runner/.local/share/virtualenvs/python-manchester-code-EDwhn3uB/lib/python3.8/site-packages/pylint/interfaces.py)
> ##[error]Process completed with exit code 1.